Switch to npm 5.6.0 as the min version
`node make.js build --task InstallAppleProvisioningProfile` failed with:

```
tsc tool:
Version 2.3.4
C:\Users\chrisid\Source\Repos\vsts-tasks2\node_modules\.bin\tsc
npm tool:
3.10.10
ERROR: Expected 5.6.0 or higher. To fix, run: npm install -g npm
```